package com.fatimacarneiro.estudokotlin.telephonenumber

enum class DDD (val prefix: Int, val state: String) {
    ONZE(11,	"São Paulo"),
    DOZE(12,	"São Paulo"),
    TREZE(13,	"São Paulo"),
    QUATORZE(14,	"São Paulo"),
    QUINZE(15,	"São Paulo"),
    DEZESSEIS(16,	"São Paulo"),
    DEZESSETE(17,	"São Paulo"),
    DEZOITO(18,	"São Paulo"),
    DEZENOVE(19,	"São Paulo"),
    VINTE_UM(21,	"Rio de Janeiro"),
    VINTE_DOIS(22,	"Rio de Janeiro"),
    VINTE_QUATRO(24,	"Rio de Janeiro"),
    VINTE_SETE(27,	"Espírito Santo"),
    VINTE_OITO(28,	"Espírito Santo"),
    TRINTA_UM(31,	"Minas Gerais"),
    TRINTA_DOIS(32,	"Minas Gerais"),
    TRINTA_TRES(33,	"Minas Gerais"),
    TRINTA_QUATRO(34,	"Minas Gerais"),
    TRINTA_CINCO(35,	"Minas Gerais"),
    TRINTA_SETE(37,	"Minas Gerais"),
    TRINTA_OITO(38,	"Minas Gerais"),
    QUARENTA_UM(41,	"Paraná"),
    QUARENTA_DOIS(42,	"Paraná"),
    QUARENTA_TRES(43,	"Paraná"),
    QUARENTA_QUATRO(44,	"Paraná"),
    QUARENTA_CINCO(45,	"Paraná"),
    QUARENTA_SEIS(46,	"Paraná"),
    QUARENTA_SETE(47,	"Santa Catarina"),
    QUARENTA_OITO(48,	"Santa Catarina"),
    QUARENTA_NOVE(49,	"Santa Catarina"),
    CINQUENTA_UM(51,	"Rio Grande do Sul"),
    CINQQUENTA_TRES(53,	"Rio Grande do Sul"),
    CINQUENTA_QUATRO(54,	"Rio Grande do Sul"),
    CINQUENTA_CINCO(55,	"Rio Grande do Sul"),
    SESSENTA_UM(61,	"Distrito Federal"),
    SESSENTA_DOIS(62,	"Goiás"),
    SESSENTA_TRES(63,	"Tocantins"),
    SESSENTA_QUATRO(64,	"Goiás"),
    SESSENTA_CINCO(65,	"Mato Grosso"),
    SESSENTA_SEIS(66,	"Mato Grosso"),
    SESSENTA_SETE(67,	"Mato Grosso do Sul"),
    SESSENTA_OITO(68,	"Acre"),
    SESSENTA_NOVE(69,	"Rondônia"),
    SETENTA_UM(71,	"Bahia"),
    SETENTA_TRES(73,	"Bahia"),
    SETENTA_QUATRO(74,	"Bahia"),
    SETENTA_CINCO(75,	"Bahia"),
    SETENTA_SETE(77,	"Bahia"),
    SETENTA_NOVE(79,	"Sergipe"),
    OITENTA_UM(81,	"Pernambuco"),
    OITENTA_DOIS(82,	"Alagoas"),
    OITENTA_TRES(83,	"Paraíba"),
    OITENTA_QUATRO(84,	"Rio Grande do Norte"),
    OITENTA_CINCO(85,	"Ceará"),
    OITENTA_SEIS(86,	"Piauí"),
    OITENTA_SETE(87,	"Pernambuco"),
    OITENTA_OITO(88,	"Ceará"),
    OITENTA_NOVE(89,	"Piauí"),
    NOVENTA_UM(91,	"Pará"),
    NOVENTA_DOIS(92,	"Amazonas"),
    NOVENTA_TRES(93,	"Pará"),
    NOVENTA_QUATRO(94,	"Pará"),
    NOVENTA_CINCO(95,	"Roraima"),
    NOVENTA_SEIS(96,	"Amapá"),
    NOVENTA_SETE(97,	"Amazonas"),
    NOVENTA_OITO(98,	"Maranhão"),
    NOVENTA_NOVE(99,	"Maranhão")
}